"""Leaderboard rendering.

Families are listed in the order they are declared in ``attacks.FAMILIES`` and
then stable-sorted by ASR, so a system's worst family is at the top while
equal-scoring families keep a fixed order across systems and stay comparable
row-by-row between tables.
"""
from __future__ import annotations

import json

from .attacks import FAMILIES
from .metrics import robustness_delta
from .schema import TIER_ADVERSARIAL, TIER_CORE, TIER_HARD_NEGATIVE, TIERS

_FAMILY_ORDER = {name: i for i, name in enumerate(FAMILIES)}

HEADER = ("| System | GG-Score | core TPR | ASR | benign over-block | "
          "hard-neg over-block | p95 ms |")
DIVIDER = "|---|---|---|---|---|---|---|"


def _fmt(value, nd: int = 3) -> str:
    return "—" if value is None else f"{value:.{nd}f}"


def _cell(result: dict, key: str):
    """None whenever the underlying pool was empty — an unmeasured metric is
    printed as an em dash rather than a confident 0.000."""
    tiers, ob = result["tiers"], result["over_block"]
    if key == "core_tpr":
        return tiers[TIER_CORE]["tpr"] if tiers[TIER_CORE]["n_violating"] else None
    if key == "asr":
        return result["asr_overall"] if result["asr_by_family_detail"] else None
    if key == "benign_ob":
        return ob[TIER_ADVERSARIAL] if tiers[TIER_ADVERSARIAL]["n_allowed"] else None
    if key == "hardneg_ob":
        return ob[TIER_HARD_NEGATIVE] if tiers[TIER_HARD_NEGATIVE]["n_allowed"] else None
    raise KeyError(key)


def partial_tag(result: dict) -> str:
    if not result["partial"]:
        return ""
    covered = [t for t in TIERS if result["tiers"][t]["n"]]
    if covered and len(covered) < len(TIERS):
        return f" (PARTIAL: {' + '.join(covered)} only)"
    return f" (PARTIAL: {result['n_evaluated']}/{result['n_items']} items)"


def family_table(result: dict) -> list[str]:
    detail = result["asr_by_family_detail"]
    if not detail:
        return []
    rows = sorted(detail.items(),
                  key=lambda kv: (-kv[1]["asr"], _FAMILY_ORDER.get(kv[0], 99)))
    out = ["| family | ASR | n |", "|---|---|---|"]
    out += [f"| `{fam}` | {_fmt(d['asr'])} | {d['n']} |" for fam, d in rows]
    return out


def leaderboard_markdown(entries: list[tuple[str, dict]],
                         footer: str | None = None) -> str:
    """``entries`` is [(system label, score() result)], rendered best-first."""
    ranked = sorted(entries, key=lambda e: -e[1]["gg_score"])
    lines = ["# GuardrailsBench leaderboard", "", HEADER, DIVIDER]
    for label, r in ranked:
        lines.append(
            f"| {label}{partial_tag(r)} | {_fmt(r['gg_score'])} | "
            f"{_fmt(_cell(r, 'core_tpr'))} | {_fmt(_cell(r, 'asr'))} | "
            f"{_fmt(_cell(r, 'benign_ob'))} | {_fmt(_cell(r, 'hardneg_ob'))} | "
            f"{r['latency']['p95_ms']:.1f} |"
        )
    lines += ["", "## Attack success rate by family", ""]
    for label, r in ranked:
        table = family_table(r)
        if not table:
            continue
        lines += [f"### {label}{partial_tag(r)}", ""] + table + [""]
    if footer:
        lines += ["---", "", footer]
    return "\n".join(lines).rstrip() + "\n"


def effective_n_note(eff: dict) -> str:
    """Spell out where a column has fewer distinct items than it appears to.

    A tier built from templates reports a rate over its item count, but the
    precision of that rate is set by distinct renderings — and under a
    cluster-disjoint split, by clusters.
    """
    thin = [(tier, n) for tier, n in eff.items() if n["clusters"] < 20]
    if not thin:
        return ""
    parts = "; ".join(f"`{tier}` is {n['items']} items but {n['distinct']} distinct "
                      f"renderings in {n['clusters']} clusters" for tier, n in thin)
    return (f"- **Effective sample size**: {parts}. Rates over those tiers are far "
            f"less precise than the item counts suggest, and a held-out system "
            f"meets their templates all-or-nothing.\n")


def provenance(data_path, n_items: int, max_overblock: float,
               train_path=None, n_folds: int = 5, eff: dict | None = None,
               incumbent_csv=None) -> str:
    """The note under the table. A leaderboard without its operating point and
    its train/eval arrangement is not reproducible, and not comparable."""
    how = (f"a held-out split (`{train_path}`)" if train_path else
           f"cluster-disjoint {n_folds}-fold cross-validation over the eval set "
           "(no system is scored by a model that saw its cluster)")
    return (
        f"Generated by `python -m guardrailsbench leaderboard --data {data_path}`.\n\n"
        f"- **Dataset**: `{data_path}`, {n_items} items.\n"
        f"- **Operating point**: thresholds calibrated to keep over-block "
        f"≤ {max_overblock:.0%} on calibration data. The over-block columns are "
        f"measured on held-out items, so they can and do exceed the budget — that "
        f"gap is how far the operating point fails to generalise.\n"
        f"- **Fitting and calibration**: {how}.\n"
        f"{effective_n_note(eff or {})}"
        + (f"- `incumbent-replay` replays the shipped guardrail's recorded "
           f"verdicts from `{incumbent_csv}`. It covers the core tier only: "
           f"adversarial items inherit `origin_id` from the seed row they came "
           f"from, and reusing that verdict for transformed text would be a "
           f"fabricated result.\n" if incumbent_csv else
           "- `incumbent-replay` is absent: it replays the shipped guardrail's "
           "recorded verdicts from the seed CSV. Run it with `--incumbent-csv`.\n")
    )


def summary_text(label: str, result: dict) -> str:
    """One system, verbosely — what the leaderboard row does not have room for."""
    c = result["components"]
    s = result["stage_attribution"]
    lines = [
        f"{label}",
        f"  GG-Score        {result['gg_score']:.3f}"
        f"   (coverage {result['coverage']:.3f}, "
        f"uncovered {result['gg_score_uncovered']:.3f})",
        "  components      " + "  ".join(f"{k}={v:.3f}" for k, v in c.items()),
        f"  robustness Δ    {robustness_delta(result):+.3f}"
        "   (clean TPR - adversarial TPR)",
        f"  over-block      overall={result['over_block']['overall']:.3f}"
        f"  core={result['over_block'][TIER_CORE]:.3f}"
        f"  hard-neg={result['over_block'][TIER_HARD_NEGATIVE]:.3f}"
        f"  benign-mirror={result['over_block'][TIER_ADVERSARIAL]:.3f}",
        f"  stage           input={s['input_caught']:.3f}"
        f"  output={s['output_caught']:.3f}  leaked={s['leaked']:.3f}",
        f"  latency ms      p50={result['latency']['p50_ms']:.1f}"
        f"  p95={result['latency']['p95_ms']:.1f}"
        f"  p99={result['latency']['p99_ms']:.1f}",
    ]
    return "\n".join(lines)


def write_result_json(path, label: str, result: dict) -> None:
    with open(path, "w") as f:
        json.dump({"system": label, **result}, f, indent=2, sort_keys=True)
